apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-api-cc2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dummy-api-cc2
  template:
    metadata:
      labels:
        name: dummy-api-cc2
    spec:
      containers:
        - name: application
          image: bellapd/dummy-api-cc2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-api-cc2
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    name: dummy-api-cc2
